# Site settings
title: 海之林
header-img: "img/Xacebook.jpg"
tagline: "cn"  
description: "王海林|学而思，勤习之"  
baseurl: ""
url: "http://wanghailin.info"  

# About/contact
owner: 
  name: " hailinn"
  email: hailln@163.com
  bio: "hailinn"

# Data
gavatar: http://openmindclub.qiniudn.com/omt/favicon.png 
favicon: img/favicon.ico

douban_username:  cnfeat
twitter_username: feat
github_username: cnfeat
facebook_username: 
weibo_username: cnfeat 
zhihu_username: feat

# Build settings  
# use Github Flavored Markdown !important  
# document: http://jekyllrb.com/docs/configuration/#kramdown  
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 15
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone: Asia/Shanghai

# Defaults for posts
defaults:
    scope: 
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Hailinn"
      header-img: "img/green.jpg" # We don't want posts without a header image, that whould mean white on white

# Comments 
comments :
  provider : disqus
  duoshuo :
    short_name :Taolity
  disqus :
      short_name : Taolity

# Analytics and webmaster tools stuff goes here
google_analytics: UA-80884545-1
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Links to include in footer navigation
