# Site settings
title: "学而勤习之"
header-img: "img/Just magic.jpg"
tagline: "cn"  
description: "Hailin|学而勤习之"  
baseurl: ""
url: "https://wanghailin.info"  

# About/contact
owner: 
  name: " Hailin"
  email: hailln@163.com
  bio: "Hailin"

# Data
gavatar: img/taolity.png
favicon: img/tolity.ico

douban_username:  
twitter_username: modaochi
github_username: Taolity
facebook_username: 
weibo_username: 
zhihu_username: wang-can-23-70

# Build settings  
# use Github Flavored Markdown !important  
# document: http://jekyllrb.com/docs/configuration/#kramdown  
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 15
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone: Asia/Shanghai

# Defaults for posts
defaults:
    scope: 
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Hailin"
      header-img: "img/blue.jpg" # We don't want posts without a header image, that whould mean white on white

# Comments 
 comments :
   provider : # disqus
  duoshuo :
    short_name : # https-www-wanghailin-info
  disqus :
      short_name : # https-www-wanghailin-info

# Analytics and webmaster tools stuff goes here
# google_analytics: # UA-80884545-1
 google_verify:
 # https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
 bing_verify:

# Links to include in footer navigation
